$(function()
{
	$('#endDateTime').data("DateTimePicker").date(moment());
	$('#startDateTime').data("DateTimePicker").date(moment());
	$("#reserve").prop("disabled",false);
	$("#reserve").click(function(event){reserve(event)});
	$("#showReservationDetails").hide();
	$("#myReservationsLink").click(function(event){showMyReservations()});
	$("#createReservationLink").click(function(event){showCreateReservation()});
	$("#myCredentialsLink").click(function(event){showMyCredentials()});
});
